version: '3.6'

volumes:
  feeder-mysql-db:

networks:
  feeder:
    name: feeder
    driver: bridge

services:

  feeder-mysql:
    container_name: feeder-mysql
    image: mysql:5.7.12
    networks:
      - feeder
    hostname: feeder-mysql
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
      - feeder-mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--sql-mode=ALLOW_INVALID_DATES','--default_time_zone=+00:00','--max_connections=1000']
    ports:
      - 3322:3306
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"
