version: '3.6'

services:

  feeder-application:
    container_name: feeder-application
    image: feederr/application
    networks:
      - feeder
    hostname: feeder-application
    depends_on:
      - feeder-mysql
      - feeder-kafka
    environment:
      - datasource.host=feeder-mysql
      - datasource.port=3306
      - bootstrap.servers=localhost:9092
    ports:
      - 8081:8081
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  feeder-authorization:
    container_name: feeder-authorization
    image: feederr/authorization
    networks:
      - feeder
    hostname: feeder-authorization
    depends_on:
      - feeder-mysql
      - feeder-kafka
    environment:
      - datasource.host=feeder-mysql
      - datasource.port=3306
      - bootstrap.servers=localhost:9092
    ports:
      - 8082:8082
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  feeder-statistics:
    container_name: feeder-statistics
    image: feederr/statistics
    networks:
      - feeder
    hostname: feeder-statistics
    depends_on:
      - feeder-mysql
      - feeder-kafka
    environment:
      - datasource.host=feeder-mysql
      - datasource.port=3306
      - bootstrap.servers=localhost:9092
    ports:
      - 8083:8083
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  feeder-api-gateway:
    container_name: feeder-api-gateway
    image: feederr/api-gateway
    networks:
      - feeder
    hostname: feeder-api-gateway
    environment:
      - application-service=feeder-application
      - authorization-service=feeder-authorization
      - statistics-service=feeder-statistics
    ports:
      - 8080:8080
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
